### ISSUE TITLE
ERROR: Cannot locate specified Dockerfile: Dockerfile

### ISSUE THREAD

**Issue by mRicooo** [experius/SeoSnap#1]
Hello,

I am trying to install your solution but after running this command docker-compose up --build -d && docker-compose down, I get this error
`ERROR: Cannot locate specified Dockerfile: Dockerfile`

Is there something I forgot or the file is really missing ?

Thank you

**Comment by egordm** [comment]
Hey mRicooo,

Can you confirm you did recursive clone?
`git clone --recursive git@github.com:experius/SeoSnap.git` 
Are there files in seosnap-cacheserver, seosnap-cachewarmer and seosnap-dashboard?
If these folders are empty, you can run the following command to pull their contents:
`git submodule update --init --recursive`
After that docker-compose up should work.

**Comment by mRicooo** [comment]
Hey EgorDm

The server was doing weird things,  I tried on an another one and It's working fine now. I can acces to the dashboard and start testing SeoSnap
Ignore my issue :) and thanks for your time
