### ISSUE TITLE
Cache issue

### ISSUE THREAD

**Issue by mRicooo** [experius/SeoSnap#11]
Hello,

I got a weird behavior that I can't really understand.
My pages are well generated with the last update in the cache folder but some of them are still showing an old version.
Is there a cache to clean or something else ?

I am using the 0.2 version.

Thank you for your help.

**Comment by egordm** [comment]
Hey @mRicooo,

There isn't an explicit cache flush command. 
You can modify your request to invalidate a single page or a single page with all it's subpaths (see https://github.com/experius/SeoSnap-Cache-Server#usage). Use the base URL of a website to flush the cache for a whole website.
Similarly, the cache warmer has the --recache BOOLEAN property to invalidate page first.

**Comment by mRicooo** [comment]
Hello ErgorDM,

Thanks for your reply.

One more question, it's possible to increase the duration of the page generation ? Some page are not well fully 100% generated 

Thank you

**Comment by egordm** [comment]
Hey @mRicooo ,

You probably need to change rendertron settings for that. I think it is the timeout config setting (see [docs](https://github.com/GoogleChrome/rendertron#config)).

You can change the rendertron config [here](https://github.com/experius/SeoSnap-Cache-Server/blob/master/rendertron-config.json). You also probably will need to rebuild the container unless you setup docker-compose to mount a config over the existing one.

**Comment by mRicooo** [comment]
Hello @EgorDm 

It's working well ! 
Thank you again for your assistance
