### ISSUE TITLE
Docker Images Name Are Wrong?

### ISSUE THREAD

**Issue by luongvm** [experius/SeoSnap#19]
When I tried to `docker-compose up`, the images cannot be found. I think the images name are wrong

If this is your package (https://hub.docker.com/r/experiusnl/seosnap-dashboard) then the docker-compose.yml in releases need to be updated

**Comment by egordm** [comment]
Hey @joturako ,

Looks like they are indeed wrong. It should be under experiusnl user.
The fix is in release 0.4.1.
Thanks for reporting.
