### ISSUE TITLE
Missing Docker image semver tags

### ISSUE THREAD

**Issue by bordeo** [experius/SeoSnap#24]
Docker image numeric tags are missing in docker hub for all seosnap images:

- https://hub.docker.com/r/experiusnl/seosnap-cacheserver/tags
- https://hub.docker.com/r/experiusnl/seosnap-cachewarmer/tags
- https://hub.docker.com/r/experiusnl/seosnap-dashboard/tags

Semver tags is very usefull for stability. For example using in kubernetes with helm chart.

Could you build and push all tags?

**Comment by lewisvoncken** [comment]
Hi @bordeo 

Thanks for the feedback!

Semver tags has been added in the docker build

- seosnap-cacheserver is deprecated we now use the experius/rendertron image directly
- seosnap-cachewarmer has build 0.4.0 & latest
- seosnap-dashboard has build 0.4.0 & latest
- experius/rendertron has build latest, 3.1.0, 3.0.0 & 3.2.0
