### ISSUE TITLE
Running SeoSnap Dashboard on a different port

### ISSUE THREAD

**Issue by multidimensionro** [experius/SeoSnap#8]
Hello,

I am having some issues with running this on a different port.

We already have a chain used on production sites: nginx (443)->varnish(80)->httpd(8080), so I would need the dashboard to run on a different port.

I've tried to modify the dashboard port to somenthing else (8090), but I am getting the following error:

ERROR: Failed to Setup IP tables: Unable to enable SKIP DNAT rule:  (iptables failed: iptables --wait -t nat -I DOCKER -i br-ffb388f86d1c -j RETURN: iptables: No chain/target/match by that name.

Please advise.

Best regards,
Sorin

**Comment by egordm** [comment]
Hey,

Weird error indeed. Does restarting the docker daemon fix it?
Also, how did you change the port on which the dashboard runs? 
* By remapping its port in docker-compose (8080:8080 -> 8080:8090)?
* Or changing it in the startup script:
    * docker-compose: 8080:8080 -> 8090:8090 
    * and setup.sh in dashboard folder "python manage.py runserver 0.0.0.0:8080" -> "python manage.py runserver 0.0.0.0:8090"
    * note: requires rebuilding the container

Have you tried them both? If so, do they both give the same error?

**Comment by multidimensionro** [comment]
Hi,

I tried the first option in docker-compose. Should I do the second?

Also the error appears during the build.

Thank you.

**Comment by multidimensionro** [comment]
Hi,

This can be closed. It was an issue with the docker service, which didn't create a chain on initialization. 

I fixed it following: https://github.com/moby/moby/issues/16816

Thank you.
